steps:

- name: 'gcr.io/cloud-builders/gcloud'
  id: "standard"
  args: ['builds','submit','--region=us-central1','--config=ci/cloudbuild.yaml','--substitutions','TAG_NAME=$TAG_NAME,COMMIT_SHA=$COMMIT_SHA,_BUILD_TYPE=']

- name: 'gcr.io/cloud-builders/gcloud'
  id: "asan"
  entrypoint: bash
  args:
    - -c
    - |
      if [ -z "$TAG_NAME" ]
      then
        gcloud builds submit --region=us-central1 --config=ci/cloudbuild.yaml --substitutions COMMIT_SHA=$COMMIT_SHA,_BUILD_TYPE=clang-asan
      fi
  waitFor: ['-']

timeout: 20000s
